/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sanji_image_feature_Gist */

#ifndef _Included_sanji_image_feature_Gist
#define _Included_sanji_image_feature_Gist
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sanji_image_feature_Gist
 * Method:    extract
 * Signature: ([III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_sanji_image_feature_Gist_extract
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
