/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_HelloJni */

#ifndef _Included_hello_HelloJni
#define _Included_hello_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_HelloJni
 * Method:    echo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hello_HelloJni_echo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
